### ISSUE TITLE
微调时，模型评估出错

### ISSUE THREAD

**Issue by leechenggg** [csuhan/VFA#12]
我用自己的数据集（mate-rcnn可跑通）使用基训练时，模型训练评估没有任何问题。在微调阶段，模型可训练也可保存，但是无法评估，换个配置环境也不行

```
2023-06-01 16:46:07,131 - mmdet - INFO - starting model initialization...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 30/30, 7.4 task/s, elapsed: 4s, ETA:     0s2023-06-01 16:46:11,222 - mmdet - INFO - model initialization done.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 139/139, 10.9 task/s, elapsed: 13s, ETA:     0s
---------------iou_thr: 0.5---------------
Traceback (most recent call last):
  File "train.py", line 252, in <module>
    main()
  File "train.py", line 248, in main
    meta=meta)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmfewshot-0.1.0-py3.7.egg/mmfewshot/detection/apis/train.py", line 206, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 262, in after_train_iter
    self._do_evaluate(runner)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmfewshot-0.1.0-py3.7.egg/mmfewshot/detection/core/evaluation/eval_hooks.py", line 50, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 362, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmfewshot-0.1.0-py3.7.egg/mmfewshot/detection/datasets/voc.py", line 470, in evaluate
    use_legacy_coordinate=True)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmfewshot-0.1.0-py3.7.egg/mmfewshot/detection/core/evaluation/mean_ap.py", line 153, in eval_map
    mean_ap, eval_results, classes, area_ranges, logger=logger)
  File "/root/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/core/evaluation/mean_ap.py", line 502, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: tuple index out of range
```

**Comment by leechenggg** [comment]
已解决，应在配置文件里修改num_class

**Comment by qjh666888** [comment]
你好，我想问一下，训练自己的数据集时，怎么指定base类和noval类的呢
