### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by wmyname** [csuhan/VFA#13]
Hello Dear author, I ran into this problem when running a few shot training on a single gpu. I look forward to your reply. Thank you

Traceback (most recent call last):
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 225, in main
    build_dataset(
  File "/home/tcs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmfewshot/detection/datasets/builder.py", line 95, in build_dataset
    dataset = NWayKShotDataset(
  File "/home/tcs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmfewshot/detection/datasets/dataset_wrappers.py", line 332, in __init__
    self.prepare_support_shots()
  File "/home/tcs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmfewshot/detection/datasets/dataset_wrappers.py", line 388, in prepare_support_shots
    self.num_support_shots // num_gts + 1)
ZeroDivisionError: integer division or modulo by zero

**Comment by hhxzzy** [comment]
hallo, how did you fix this problem?

**Comment by wmyname** [comment]
The support-shot generated by "prepare_voc_few_shot.py" is empty. You can search for "prepare_voc_few_shot.py" from the Internet and run it several times.
